{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}-secrets
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  API_KEY: {{ .Values.secret.API_KEY | quote }}
{{- end }}
